# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7, 7)
x

tensor([[0.4163, 0.7757, 0.3529, 0.8354, 0.5981, 0.7729, 0.0726],
        [0.0487, 0.0284, 0.5132, 0.2545, 0.6759, 0.9774, 0.6606],
        [0.7399, 0.4713, 0.2268, 0.2619, 0.6709, 0.5541, 0.4935],
        [0.8908, 0.9054, 0.8469, 0.3877, 0.5719, 0.4538, 0.3299],
        [0.1163, 0.8381, 0.1263, 0.2788, 0.3075, 0.1396, 0.1687],
        [0.5052, 0.4411, 0.2721, 0.6485, 0.7259, 0.6342, 0.5030],
        [0.1575, 0.7154, 0.5561, 0.8638, 0.1911, 0.4523, 0.6733]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
y = torch.rand(1, 7)

# Perform matrix multiplication 
torch.matmul(x, y.T)

tensor([[2.1835],
        [1.6794],
        [2.0964],
        [2.7212],
        [1.1491],
        [2.0640],
        [2.0400]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
SEED = 0
torch.manual_seed(SEED)

# Create two random tensors
x0 = torch.rand(7,7)
y0 = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(x0, y0.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU

# NO GPU


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
SEED = 1234
torch.manual_seed(SEED)

# Create random tensor
a = torch.rand(2,3)
b = torch.rand(2,3)

# Create two random tensors on GPU
# I have no GPU (

a, b

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
c = torch.matmul(a, b.T)
c

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
# Find min
c.max(), c.min()

(tensor(0.5617), tensor(0.3647))

### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
# Find arg min
c.argmax(), c.argmin()

(tensor(3), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
SEED = 7
torch.manual_seed(SEED)

# Create random tensor
z = torch.rand(1, 1, 1, 10)

# Remove single dimensions
z0 = z.squeeze()

# Print out tensors and their shapes
z, z.shape, z0, z0.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))